services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-stack

  redis:
    image: redis:7.0-alpine
    container_name: radio-monoko-redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - internal-stack
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    restart: always
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - NODE_ENV=production
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - internal-stack

  web:
    build:
      context: ./radioMonoco_Web
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    env_file: .env
    volumes:
      - ./radioMonoco_Web:/usr/src/app:delegated
      - web_node_modules:/usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://api
    networks:
      - internal-stack
    depends_on:
      - api

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./mobile:/usr/src/app:delegated
      - mobile_node_modules:/usr/src/app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
    networks:
      - internal-stack
    depends_on:
      - api

networks:
  internal-stack:
    driver: bridge

volumes:
  redis-data:
    driver: local
  postgres_data:
    driver: local
  web_node_modules:
    driver: local
  mobile_node_modules:
    driver: local
